input_dir: /n/data1/hms/dbmi/farhat/ye12/who
output_dir: /n/data1/hms/dbmi/farhat/Sanjana/who-mutation-catalogue
binary: true
atu_analysis: true
atu_analysis_type: CC
pheno_category_lst:
- WHO
- ALL
tiers_lst:
- '1'
- '2'
pool_type: "poolSeparate"
synonymous: false
amb_mode: DROP
AF_thresh: 0.75
missing_isolate_thresh: 0.01
missing_feature_thresh: 0.25
drop_isolates_before_variants: false
impute: false
num_PCs: 5
num_bootstrap: 1000
alpha: 0.05
